install:
	pip install virtualenv
.PHONY: install

create:
	virtualenv ~/.virtualenvs/chalice-text-classifier
.PHONY: create

source:
	source ~/.virtualenvs/chalice-text-classifier/bin/activate
.PHONY: source

install-chalice:
	pip install chalice
.PHONY: install-chalice


create-project: 
	chalice new-project project
.PHONY: create-project


